version: "3.7"
services:
  mc_server:
    image: minio/minio
    command: server /data
  mc_client:
    build:
      context: test/docker
      args:
        http_proxy: ${http_proxy}
        https_proxy: ${https_proxy}
        no_proxy: ${no_proxy}, mc_server
    volumes:
      - .:/code
